package com.m365api.controller;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Arrays;
import java.util.Objects;
import java.util.stream.Collectors;

import org.json.CDL;
import org.json.JSONArray;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;

@RestController
public class M365APIController {
	@Autowired
	private RestTemplate restTemplate;

	@GetMapping("/get1")
	public Object getSubscribedSkus() {
		String token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6Img2UEZlSmRfUDBjZmR1NlhDZEp2RXY5bXJZOUp1MmJILUtZRzZLeGNJckEiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wMDg2NGI2MC02NjE1LTQ4YTAtYjFkYS02Njc3OTU2OTg0MDUvIiwiaWF0IjoxNjgzMjExNDIyLCJuYmYiOjE2ODMyMTE0MjIsImV4cCI6MTY4MzI5ODEyMiwiYWlvIjoiRTJaZ1lBaXdZL2E3dnVhRWFkQVB1NzNmdzF3T0FBQT0iLCJhcHBfZGlzcGxheW5hbWUiOiJHcmFwaEFQSUFjY2VzcyIsImFwcGlkIjoiMGRhNzRmNDYtYTUxOC00Y2Y0LWFhZmEtMmZhMzMzNTY1MzFiIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMDA4NjRiNjAtNjYxNS00OGEwLWIxZGEtNjY3Nzk1Njk4NDA1LyIsImlkdHlwIjoiYXBwIiwib2lkIjoiZjBmYjI4OTUtMDZhMC00MzczLWI1MzYtNjkzMmQ1MjlkNmFlIiwicmgiOiIwLkFYSUFZRXVHQUJWbW9FaXgybVozbFdtRUJRTUFBQUFBQUFBQXdBQUFBQUFBQUFCeUFBQS4iLCJyb2xlcyI6WyJVc2VyLlJlYWRXcml0ZS5BbGwiLCJEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCIsIkNhbGxSZWNvcmRzLlJlYWQuQWxsIiwiRGlyZWN0b3J5LlJlYWQuQWxsIiwiVXNlci5SZWFkLkFsbCIsIlJlcG9ydHMuUmVhZC5BbGwiXSwic3ViIjoiZjBmYjI4OTUtMDZhMC00MzczLWI1MzYtNjkzMmQ1MjlkNmFlIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiMDA4NjRiNjAtNjYxNS00OGEwLWIxZGEtNjY3Nzk1Njk4NDA1IiwidXRpIjoiakstd1dORFZoVTZ1U0RUMFZPWmtBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiMDk5N2ExZDAtMGQxZC00YWNiLWI0MDgtZDVjYTczMTIxZTkwIl0sInhtc19jYyI6WyJDUDEiXSwieG1zX3NzbSI6IjEiLCJ4bXNfdGNkdCI6MTU0NDc5NzA0MH0.FI7adgM7KKruvhOogQG6BlHAK3wqOYjl3Pd5ZPP8ATwW7FWSMiCy549sBW3Y45DTc2_xzMGMkp50Q7pINaGLJKr01eSzhNYSfKB1cADlV2_p3j7kJz1oxEug9mPC65RaHouFLjbzJ5ZQjq3ceupIdhaR9mI34_hso_04jFBwINRxIY-kI6BmEoXgEiHVRjKh3MALvKCuN91ZfZigU6FQP_4FrH3rrLp2bXt21O86vBAQ7jVu85kuQledj9OT91xhKIdPRJKtC16RGWr1Gxo2ktOErHrXN4HGPYy3Kn6ZfG7QoG69flAQaYK9Fbs-US4Wb5I9EAZ7yZMWpfltuvghxg";

		HttpHeaders headers = new HttpHeaders();
		headers.setAccept(Arrays.asList(MediaType.APPLICATION_JSON));
		headers.add("user-agent",
				"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36");
		headers.setBearerAuth(token);
		HttpEntity<String> entity = new HttpEntity<String>(headers);

		return restTemplate
				.exchange("https://graph.microsoft.com/v1.0/subscribedSkus", HttpMethod.GET, entity, Object.class)
				.getBody();
	}

	@GetMapping("/get2")
	public Object getOffice365ActivationsUserCounts() {

		String token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6Img2UEZlSmRfUDBjZmR1NlhDZEp2RXY5bXJZOUp1MmJILUtZRzZLeGNJckEiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wMDg2NGI2MC02NjE1LTQ4YTAtYjFkYS02Njc3OTU2OTg0MDUvIiwiaWF0IjoxNjgzMjExNDIyLCJuYmYiOjE2ODMyMTE0MjIsImV4cCI6MTY4MzI5ODEyMiwiYWlvIjoiRTJaZ1lBaXdZL2E3dnVhRWFkQVB1NzNmdzF3T0FBQT0iLCJhcHBfZGlzcGxheW5hbWUiOiJHcmFwaEFQSUFjY2VzcyIsImFwcGlkIjoiMGRhNzRmNDYtYTUxOC00Y2Y0LWFhZmEtMmZhMzMzNTY1MzFiIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMDA4NjRiNjAtNjYxNS00OGEwLWIxZGEtNjY3Nzk1Njk4NDA1LyIsImlkdHlwIjoiYXBwIiwib2lkIjoiZjBmYjI4OTUtMDZhMC00MzczLWI1MzYtNjkzMmQ1MjlkNmFlIiwicmgiOiIwLkFYSUFZRXVHQUJWbW9FaXgybVozbFdtRUJRTUFBQUFBQUFBQXdBQUFBQUFBQUFCeUFBQS4iLCJyb2xlcyI6WyJVc2VyLlJlYWRXcml0ZS5BbGwiLCJEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCIsIkNhbGxSZWNvcmRzLlJlYWQuQWxsIiwiRGlyZWN0b3J5LlJlYWQuQWxsIiwiVXNlci5SZWFkLkFsbCIsIlJlcG9ydHMuUmVhZC5BbGwiXSwic3ViIjoiZjBmYjI4OTUtMDZhMC00MzczLWI1MzYtNjkzMmQ1MjlkNmFlIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiMDA4NjRiNjAtNjYxNS00OGEwLWIxZGEtNjY3Nzk1Njk4NDA1IiwidXRpIjoiakstd1dORFZoVTZ1U0RUMFZPWmtBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiMDk5N2ExZDAtMGQxZC00YWNiLWI0MDgtZDVjYTczMTIxZTkwIl0sInhtc19jYyI6WyJDUDEiXSwieG1zX3NzbSI6IjEiLCJ4bXNfdGNkdCI6MTU0NDc5NzA0MH0.FI7adgM7KKruvhOogQG6BlHAK3wqOYjl3Pd5ZPP8ATwW7FWSMiCy549sBW3Y45DTc2_xzMGMkp50Q7pINaGLJKr01eSzhNYSfKB1cADlV2_p3j7kJz1oxEug9mPC65RaHouFLjbzJ5ZQjq3ceupIdhaR9mI34_hso_04jFBwINRxIY-kI6BmEoXgEiHVRjKh3MALvKCuN91ZfZigU6FQP_4FrH3rrLp2bXt21O86vBAQ7jVu85kuQledj9OT91xhKIdPRJKtC16RGWr1Gxo2ktOErHrXN4HGPYy3Kn6ZfG7QoG69flAQaYK9Fbs-US4Wb5I9EAZ7yZMWpfltuvghxg";

		HttpHeaders headers = new HttpHeaders();
		headers.setAccept(Arrays.asList(MediaType.APPLICATION_OCTET_STREAM));
		headers.setBearerAuth(token);
		HttpEntity<String> entity = new HttpEntity<String>(headers);
		System.out.println("++++++++++++++++++++++++++++++");
		Object responseEntity = this.restTemplate
				.exchange("https://graph.microsoft.com/v1.0/reports/getOffice365ActivationsUserCounts", HttpMethod.GET,
						entity, String.class)
				.getBody();
		System.out.println("---------------" + responseEntity);
		return responseEntity;
	}

	@GetMapping("/get3")
	public JSONArray getRespoInputStreamReader() throws Exception {
		URL url = new URL("https://graph.microsoft.com/v1.0/reports/getOffice365GroupsActivityFileCounts(period='D7')");
		HttpURLConnection conn = (HttpURLConnection) url.openConnection();
		String token = "eyJ0eXAiOiJKV1QiLCJub25jZSI6Img2UEZlSmRfUDBjZmR1NlhDZEp2RXY5bXJZOUp1MmJILUtZRzZLeGNJckEiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyIsImtpZCI6Ii1LSTNROW5OUjdiUm9meG1lWm9YcWJIWkdldyJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8wMDg2NGI2MC02NjE1LTQ4YTAtYjFkYS02Njc3OTU2OTg0MDUvIiwiaWF0IjoxNjgzMjExNDIyLCJuYmYiOjE2ODMyMTE0MjIsImV4cCI6MTY4MzI5ODEyMiwiYWlvIjoiRTJaZ1lBaXdZL2E3dnVhRWFkQVB1NzNmdzF3T0FBQT0iLCJhcHBfZGlzcGxheW5hbWUiOiJHcmFwaEFQSUFjY2VzcyIsImFwcGlkIjoiMGRhNzRmNDYtYTUxOC00Y2Y0LWFhZmEtMmZhMzMzNTY1MzFiIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvMDA4NjRiNjAtNjYxNS00OGEwLWIxZGEtNjY3Nzk1Njk4NDA1LyIsImlkdHlwIjoiYXBwIiwib2lkIjoiZjBmYjI4OTUtMDZhMC00MzczLWI1MzYtNjkzMmQ1MjlkNmFlIiwicmgiOiIwLkFYSUFZRXVHQUJWbW9FaXgybVozbFdtRUJRTUFBQUFBQUFBQXdBQUFBQUFBQUFCeUFBQS4iLCJyb2xlcyI6WyJVc2VyLlJlYWRXcml0ZS5BbGwiLCJEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCIsIkNhbGxSZWNvcmRzLlJlYWQuQWxsIiwiRGlyZWN0b3J5LlJlYWQuQWxsIiwiVXNlci5SZWFkLkFsbCIsIlJlcG9ydHMuUmVhZC5BbGwiXSwic3ViIjoiZjBmYjI4OTUtMDZhMC00MzczLWI1MzYtNjkzMmQ1MjlkNmFlIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6IkFTIiwidGlkIjoiMDA4NjRiNjAtNjYxNS00OGEwLWIxZGEtNjY3Nzk1Njk4NDA1IiwidXRpIjoiakstd1dORFZoVTZ1U0RUMFZPWmtBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiMDk5N2ExZDAtMGQxZC00YWNiLWI0MDgtZDVjYTczMTIxZTkwIl0sInhtc19jYyI6WyJDUDEiXSwieG1zX3NzbSI6IjEiLCJ4bXNfdGNkdCI6MTU0NDc5NzA0MH0.FI7adgM7KKruvhOogQG6BlHAK3wqOYjl3Pd5ZPP8ATwW7FWSMiCy549sBW3Y45DTc2_xzMGMkp50Q7pINaGLJKr01eSzhNYSfKB1cADlV2_p3j7kJz1oxEug9mPC65RaHouFLjbzJ5ZQjq3ceupIdhaR9mI34_hso_04jFBwINRxIY-kI6BmEoXgEiHVRjKh3MALvKCuN91ZfZigU6FQP_4FrH3rrLp2bXt21O86vBAQ7jVu85kuQledj9OT91xhKIdPRJKtC16RGWr1Gxo2ktOErHrXN4HGPYy3Kn6ZfG7QoG69flAQaYK9Fbs-US4Wb5I9EAZ7yZMWpfltuvghxg";
		conn.setRequestProperty("Accept", "application/octet-stream");
		conn.setRequestProperty("Authorization", "Bearer " + token);
		conn.setRequestMethod("GET");
		String csv = new BufferedReader(new InputStreamReader(Objects.requireNonNull(conn.getInputStream()), StandardCharsets.UTF_8)).lines().collect(Collectors.joining("\n"));
		JSONArray json = CDL.toJSONArray(csv);
		return json;
	}
}